// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Query struct {
}

type Response struct {
	Content string `json:"content"`
	Done    bool   `json:"done"`
}

type Subscription struct {
}
